# Generated by Django 4.1.3 on 2022-11-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertext',
            field=models.TextField(null=True),
        ),
    ]
