# Generated by Django 4.1 on 2022-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_usertext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usertext',
        ),
        migrations.AddField(
            model_name='user',
            name='userhash',
            field=models.TextField(default=''),
        ),
    ]
