# Generated by Django 4.1 on 2022-12-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watermark_image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(),
        ),
    ]
