# Generated by Django 4.1.3 on 2022-11-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='text_content',
            field=models.TextField(null=True),
        ),
    ]
