# Generated by Django 4.1.3 on 2022-11-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_feed_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='encrypted_image',
            field=models.TextField(null=True),
        ),
    ]
