# Generated by Django 4.1.3 on 2022-11-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_feed_encrypted_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='nickname',
            field=models.CharField(default='', max_length=24),
        ),
    ]
