# Generated by Django 4.1.3 on 2022-12-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_feed_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='userhash',
            field=models.TextField(default=''),
        ),
    ]
