# Generated by Django 4.1 on 2022-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_feed_userhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='userhash',
            field=models.TextField(default='', null=True),
        ),
    ]
